name: 'Twitch CLI Action'
description: 'Runs the Twitch CLI'
runs:
  using: 'composite'
  steps:
# Linux
    - name: Download latest Twitch CLI
      if: runner.os == 'Linux'
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'twitchdev/twitch-cli'
        version: 'latest'
        token: ${{ github.token }}
        regex: true
        file: 'twitch-cli_.*_Linux_.*\.tar\.gz'
    - name: Rename Asset
      if: runner.os == 'Linux'
      shell: bash
      run: mv twitch-cli_*_Linux_*.tar.gz twitch-cli.tar.gz
    - name: List Dir
      if: runner.os == 'Linux'
      shell: bash
      run: ls
    - name: Extract Twitch CLI
      if: runner.os == 'Linux'
      shell: bash
      run: tar -xzf twitch-cli.tar.gz 
    - name: List Dir
      if: runner.os == 'Linux'
      shell: bash
      run: ls
    - name: Prepare executable
      if: runner.os == 'Linux'
      shell: bash
      run: mv twitch-cli/twitch /usr/local/bin/twitch && chmod ug+x /usr/local/bin/twitch