name: 'Twitch CLI Action'
description: 'Runs the Twitch CLI'

inputs:
  mock:
    description: Whether to start the API Mock Server (beta)
    default: false
  events:
    description: Which Events to mock (EventSub) [Comma-seperated]
    default: ''
  eventsub_endpoint:
    description: URL of the Endpoint, which shall accept the events
    default: ''

runs:
  using: 'composite'
  steps:
# Linux & macOS
    - name: Install latest Twitch CLI
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: brew install twitchdev/twitch/twitch-cli 
      
# Windows
    - name: Set Execution Policy Scoop
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
    - name: Install Scoop
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
    - name: Add to PATH
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: echo "%USERPROFILE%/scoop/shims" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Add TwitchDev Bucket
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: scoop bucket add twitch https://github.com/twitchdev/scoop-bucket.git
    - name: Install latest Twitch CLI
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: scoop install twitch-cli