name: 'Mock Twitch API'
description: 'Starts a mock server and executes a command afterwards (optional)'

inputs:
  port:
    description: The port of the API Mock Server (beta)
    default: 8080
  command:
    description: The command to execute after starting the API Mock Server (beta)
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Start Mock Server
      shell: bash
      env:
        ACTION_TWITCH_MOCK_PORT: ${{ inputs.port }}
        ACTION_TWITCH_MOCK_COMMAND: ${{ inputs.command }}
      run: chmod u+x $GITHUB_ACTION_PATH/mock.sh && $GITHUB_ACTION_PATH/mock.sh