name: 'Twitch API Call'
description: 'Execute an API call'

inputs:
  method:
    description: The HTTP method
    required: true
  endpoint:
    description: URL of the Endpoint to call
    required: true
  query_parameters:
    description: (Comma-seperated) query parameters in the format of from_id=44635596,to_id=44635596
    default: ''

outputs:
  response:
    description: Response of the API call
    value: ${{ steps.call.outputs.response }}

runs:
  using: 'composite'
  steps:
    - name: Execute API call
      id: call
      shell: bash
      env:
        ACTION_TWITCH_METHOD: ${{ inputs.method }}
        ACTION_TWITCH_ENDPOINT: ${{ inputs.endpoint }}
        ACTION_TWITCH_QUERY_PARAMETERS: ${{ inputs.query_parameters }}
      run: chmod u+x $GITHUB_ACTION_PATH/api.sh && $GITHUB_ACTION_PATH/api.sh