name: Test Run

on:
  workflow_dispatch:

jobs:
  test:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Run
        uses: katzen48/twitch-cli-action@master
        with:
          mock_command: curl http://localhost:8080/units/users -H "Accept: application/json"
          
      - name: Get Version
        shell: bash
        run: twitch version