name: Test Run

on:
  schedule:
  - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Install
        uses: katzen48/twitch-cli-action/install@master
      - name: Get Version
        shell: bash
        run: twitch version
      - name: Configure
        uses: katzen48/twitch-cli-action/configure@master
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
      - name: Get Token
        id: token
        uses: katzen48/twitch-cli-action/token@master
      - name: Run
        uses: katzen48/twitch-cli-action@master
        with:
          mock_command: 'curl http://localhost:8080/units/users -H "Accept: application/json"'
      - name: Revoke Token
        if: ${{ always() }}
        uses: katzen48/twitch-cli-action/token@master
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          token: ${{ steps.token.outputs.token }}
