name: Test Run

on:
  schedule:
  - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Install
        uses: katzen48/twitch-cli-action/install@master
      - name: Get Version
        shell: bash
        run: twitch version
      - name: Configure
        uses: katzen48/twitch-cli-action/configure@master
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
      - name: Get Token
        id: token
        uses: katzen48/twitch-cli-action/token@master
      - name: Mock API
        uses: katzen48/twitch-cli-action/mock-api@master
        with:
          command: 'curl http://localhost:8080/units/users -H "Accept: application/json"'
      - name: Get from API
        id: api
        uses: katzen48/twitch-cli-action/api@master
        with:
          method: get
          endpoint: users
          query_parameters: login=katzen48
      - name: Echo API Response
        shell: bash
        env:
          RESPONSE: ${{ steps.api.outputs.response }}
        run: echo "$RESPONSE"
      - name: Revoke Token
        if: ${{ always() }}
        uses: katzen48/twitch-cli-action/token@master
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          token: ${{ steps.token.outputs.token }}
