name: Test Run

on:
  workflow_dispatch:

jobs:
  test:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Run
        uses: katzen48/twitch-cli-action@master
      - name: Get Version
        shell: bash
        run: twitch version